name: WLED compile

on:
  workflow_dispatch:
    inputs:
      wled_version:
        description: 'WLED Version (e.g. 0.15.3)'
        required: true
        default: '0.15.3'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://api.github.com/repos/wled/WLED/zipball/v${{ inputs.wled_version }} -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32c3dev' >>platformio.ini
        
        echo 'build_flags = ${env:esp32c3dev.build_flags} -D BTNPIN=8 -D ARDUINO_USB_CDC_ON_BOOT=0' >>platformio.ini
        echo 'build_unflags= -D WLED_RELEASE_NAME' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build

    - name: Prepare Binary
      run: |
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        OUTPUT_FILENAME="WLED_${{ inputs.wled_version }}_C3_Custom.bin"
        
        cp "${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin" "$GITHUB_WORKSPACE/$OUTPUT_FILENAME"
        
        echo "FIRMWARE_NAME=$OUTPUT_FILENAME" >> $GITHUB_ENV
        echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ inputs.wled_version }}-c3-${{ env.DATE }}
        name: WLED ${{ inputs.wled_version }} for SP530E
        
        body: |
          ### Custom Build Details
          - **Version:** ${{ inputs.wled_version }}
          - **Chip:** ESP32-C3
          - **USB CDC:** 0
        
        files: ${{ github.workspace }}/${{ env.FIRMWARE_NAME }}
        fail_on_unmatched_files: true
